version: '3'
services:
  consumer_a:
    image: alpine
    volumes:
      - "./:/app"
    command: /app/consumer -addr nsqlookupd:4161 -topic test -channel foo
  consumer_b:
    image: alpine
    volumes:
      - "./:/app"
    command: /app/consumer -addr nsqlookupd:4161 -topic test -channel foo
  consumer_c:
    image: alpine
    volumes:
      - "./:/app"
    command: /app/consumer -addr nsqlookupd:4161 -topic test -channel bar
  consumer_d:
    image: alpine
    volumes:
      - "./:/app"
    command: /app/consumer -addr nsqlookupd:4161 -topic test -channel bar
