version: '3'
services:
  pubsub_foo1:
    image: nsq-consumer
    command: /app/consumer -topic test -channel foo
  pubsub_foo2:
    image: nsq-consumer
    command: /app/consumer -topic test -channel foo
  pubsub_bar1:
    image: nsq-consumer
    command: /app/consumer -topic test -channel bar
  pubsub_bar2:
    image: nsq-consumer
    command: /app/consumer -topic test -channel bar
